import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from '../app.module';

describe('Quiz (e2e)', () => {
  let app: INestApplication;
  let adminToken: string;
  let studentToken: string;
  let studentId: string;
  let courseId: string;

  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = module.createNestApplication();
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));
    await app.init();

    // Admin
    const adminEmail = `quiz-admin-${Date.now()}@example.com`;
    await request(app.getHttpServer())
      .post('/api/auth/register')
      .send({ email: adminEmail, password: 'admin123', fullName: 'Quiz Admin', role: 'ADMIN' });
    const adminLogin = await request(app.getHttpServer())
      .post('/api/auth/login')
      .send({ email: adminEmail, password: 'admin123' });
    adminToken = adminLogin.body.accessToken;

    // Student
    const studentEmail = `quiz-student-${Date.now()}@example.com`;
    const reg = await request(app.getHttpServer())
      .post('/api/auth/register')
      .send({ email: studentEmail, password: 'student123', fullName: 'Quiz Student', role: 'STUDENT' });
    studentId = reg.body.user.id;
    const studentLogin = await request(app.getHttpServer())
      .post('/api/auth/login')
      .send({ email: studentEmail, password: 'student123' });
    studentToken = studentLogin.body.accessToken;

    // Course
    const courseRes = await request(app.getHttpServer())
      .post('/api/admin/courses')
      .set('Authorization', `Bearer ${adminToken}`)
      .send({ code: `QUIZ-${Date.now()}`, title: 'Quiz Test Course', semester: '2025-Spring' });
    courseId = courseRes.body.id;

    // Enroll student
    await request(app.getHttpServer())
      .post(`/api/admin/enrollments`)
      .set('Authorization', `Bearer ${adminToken}`)
      .send({ userId: studentId, courseId, roleInCourse: 'STUDENT' });
  });

  afterAll(async () => {
    await app.close();
  });

  const sampleQuiz = {
    title: 'Sample Quiz',
    description: 'Generated by test',
    source: 'MANUAL',
    isPublished: true,
    secondsPerQuestion: 30,
    questions: [
      {
        question: 'What is 2+2?',
        options: ['3', '4', '5', '6'],
        correctIndex: 1,
        explanation: 'basic math',
        points: 100,
      },
      {
        question: 'Capital of Kazakhstan?',
        options: ['Almaty', 'Astana', 'Bishkek', 'Tashkent'],
        correctIndex: 1,
        explanation: '',
        points: 100,
      },
    ],
  };

  let createdQuizId: string;

  it('POST /api/courses/:id/quizzes — admin creates a quiz', async () => {
    const res = await request(app.getHttpServer())
      .post(`/api/courses/${courseId}/quizzes`)
      .set('Authorization', `Bearer ${adminToken}`)
      .send(sampleQuiz);
    expect(res.status).toBe(201);
    expect(res.body).toHaveProperty('id');
    expect(res.body.title).toBe('Sample Quiz');
    expect(Array.isArray(res.body.questions)).toBe(true);
    expect(res.body.questions.length).toBe(2);
    createdQuizId = res.body.id;
  });

  it('POST /api/courses/:id/quizzes — student gets 403', async () => {
    const res = await request(app.getHttpServer())
      .post(`/api/courses/${courseId}/quizzes`)
      .set('Authorization', `Bearer ${studentToken}`)
      .send(sampleQuiz);
    expect(res.status).toBe(403);
  });

  it('GET /api/quizzes/:id — student sees correctIndex=-1', async () => {
    const res = await request(app.getHttpServer())
      .get(`/api/quizzes/${createdQuizId}`)
      .set('Authorization', `Bearer ${studentToken}`);
    expect(res.status).toBe(200);
    expect(res.body.questions.every((q: any) => q.correctIndex === -1)).toBe(true);
  });

  it('GET /api/quizzes/:id — admin sees real correctIndex', async () => {
    const res = await request(app.getHttpServer())
      .get(`/api/quizzes/${createdQuizId}`)
      .set('Authorization', `Bearer ${adminToken}`);
    expect(res.status).toBe(200);
    expect(res.body.questions[0].correctIndex).toBe(1);
  });

  it('POST /api/quizzes/:id/attempts → PATCH submit — student gets autoscore', async () => {
    const start = await request(app.getHttpServer())
      .post(`/api/quizzes/${createdQuizId}/attempts`)
      .set('Authorization', `Bearer ${studentToken}`);
    expect(start.status).toBe(201);
    const attemptId = start.body.id;

    // Fetch quiz to get question IDs
    const quiz = await request(app.getHttpServer())
      .get(`/api/quizzes/${createdQuizId}`)
      .set('Authorization', `Bearer ${adminToken}`);
    const questions = quiz.body.questions;

    // Answer correctly for Q1, wrong for Q2 → 100 / 200
    const submit = await request(app.getHttpServer())
      .patch(`/api/quizzes/${createdQuizId}/attempts/${attemptId}/submit`)
      .set('Authorization', `Bearer ${studentToken}`)
      .send({
        answers: [
          { questionId: questions[0].id, pickedIndex: 1 }, // correct
          { questionId: questions[1].id, pickedIndex: 0 }, // wrong
        ],
      });
    expect(submit.status).toBe(200);
    expect(submit.body.score).toBe(100);
    expect(submit.body.totalPoints).toBe(200);
    expect(submit.body.completedAt).not.toBeNull();
  });

  it("GET /api/quizzes/:id/attempts/me — returns student's own attempts", async () => {
    const res = await request(app.getHttpServer())
      .get(`/api/quizzes/${createdQuizId}/attempts/me`)
      .set('Authorization', `Bearer ${studentToken}`);
    expect(res.status).toBe(200);
    expect(Array.isArray(res.body)).toBe(true);
    expect(res.body.length).toBeGreaterThanOrEqual(1);
  });

  it('DELETE /api/quizzes/:id — admin soft-deletes the quiz', async () => {
    const res = await request(app.getHttpServer())
      .delete(`/api/quizzes/${createdQuizId}`)
      .set('Authorization', `Bearer ${adminToken}`);
    expect(res.status).toBe(200);
    expect(res.body.deleted).toBe(true);

    // After soft-delete, GET should return 404
    const after = await request(app.getHttpServer())
      .get(`/api/quizzes/${createdQuizId}`)
      .set('Authorization', `Bearer ${adminToken}`);
    expect(after.status).toBe(404);
  });

  // ─── Question CRUD endpoints (added with the Kahoot-style flow) ───────
  // These let teachers tweak individual questions after AI generation
  // without rebuilding the whole quiz.
  describe('Question CRUD', () => {
    let quizId: string;
    let questionIds: string[] = [];

    beforeAll(async () => {
      // Create a fresh quiz that wasn't deleted by the test above.
      const r = await request(app.getHttpServer())
        .post(`/api/courses/${courseId}/quizzes`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          title: 'Question CRUD test',
          description: '',
          isPublished: false,
          secondsPerQuestion: 30,
          questions: [
            {
              question: 'Q1',
              options: ['A', 'B', 'C', 'D'],
              correctIndex: 0,
              explanation: '',
              points: 100,
              difficulty: 'EASY',
            },
            {
              question: 'Q2',
              options: ['A', 'B', 'C', 'D'],
              correctIndex: 1,
              explanation: '',
              points: 100,
              difficulty: 'MEDIUM',
            },
          ],
        });
      quizId = r.body.id;
      questionIds = r.body.questions.map((q: any) => q.id);
    });

    it('POST /api/quizzes/:id/questions — appends with auto position', async () => {
      const before = await request(app.getHttpServer())
        .get(`/api/quizzes/${quizId}`)
        .set('Authorization', `Bearer ${adminToken}`);
      const positionsBefore = before.body.questions.map((q: any) => q.position);
      const maxPosBefore = Math.max(...positionsBefore);

      const res = await request(app.getHttpServer())
        .post(`/api/quizzes/${quizId}/questions`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          question: 'Q3 freshly added',
          options: ['A', 'B', 'C'],
          correctIndex: 2,
          explanation: 'because',
          points: 150,
          difficulty: 'HARD',
        });
      expect(res.status).toBe(201);
      expect(res.body.question).toBe('Q3 freshly added');
      expect(res.body.position).toBe(maxPosBefore + 1);
      expect(res.body.correctIndex).toBe(2);
    });

    it('POST /api/quizzes/:id/questions — rejects correctIndex out of range', async () => {
      const res = await request(app.getHttpServer())
        .post(`/api/quizzes/${quizId}/questions`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ question: 'bad', options: ['A', 'B'], correctIndex: 5 });
      expect(res.status).toBe(400);
    });

    it('PATCH /api/quiz-questions/:id — updates fields', async () => {
      const res = await request(app.getHttpServer())
        .patch(`/api/quiz-questions/${questionIds[0]}`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ question: 'Q1 (edited)', explanation: 'NEW' });
      expect(res.status).toBe(200);
      expect(res.body.question).toBe('Q1 (edited)');
      expect(res.body.explanation).toBe('NEW');
    });

    it('PATCH /api/quiz-questions/:id — validates correctIndex against options length', async () => {
      const res = await request(app.getHttpServer())
        .patch(`/api/quiz-questions/${questionIds[0]}`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ correctIndex: 99 }); // options are 4-long
      expect(res.status).toBe(400);
    });

    it('DELETE /api/quiz-questions/:id — soft-delete + reindex remaining', async () => {
      const del = await request(app.getHttpServer())
        .delete(`/api/quiz-questions/${questionIds[1]}`)
        .set('Authorization', `Bearer ${adminToken}`);
      expect(del.status).toBe(200);
      expect(del.body.deleted).toBe(true);

      const after = await request(app.getHttpServer())
        .get(`/api/quizzes/${quizId}`)
        .set('Authorization', `Bearer ${adminToken}`);
      // After deleting one question, remaining positions should be
      // contiguous starting at 0 — no gaps.
      const positions = after.body.questions.map((q: any) => q.position).sort();
      expect(positions).toEqual(positions.map((_p: number, i: number) => i));
      // The deleted question shouldn't appear.
      expect(after.body.questions.find((q: any) => q.id === questionIds[1])).toBeUndefined();
    });

    it('Student cannot modify questions (403)', async () => {
      const res = await request(app.getHttpServer())
        .patch(`/api/quiz-questions/${questionIds[0]}`)
        .set('Authorization', `Bearer ${studentToken}`)
        .send({ question: 'evil' });
      expect(res.status).toBe(403);
    });

    it('Question CRUD requires auth', async () => {
      const add = await request(app.getHttpServer()).post(`/api/quizzes/${quizId}/questions`).send({});
      expect(add.status).toBe(401);
      const patch = await request(app.getHttpServer()).patch(`/api/quiz-questions/${questionIds[0]}`).send({});
      expect(patch.status).toBe(401);
      const del = await request(app.getHttpServer()).delete(`/api/quiz-questions/${questionIds[0]}`);
      expect(del.status).toBe(401);
    });
  });

  // ─── /api/quizzes/:id/broadcast-telegram ──────────────────────────────
  // Teacher-only endpoint. We can't actually send Telegram polls in CI
  // (no bot token) but the auth/role contract should still be enforced.
  describe('Quiz → Telegram broadcast', () => {
    let bquizId: string;
    beforeAll(async () => {
      const r = await request(app.getHttpServer())
        .post(`/api/courses/${courseId}/quizzes`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          title: 'Broadcast spec',
          isPublished: true,
          questions: [{ question: 'Q', options: ['A', 'B'], correctIndex: 0 }],
        });
      bquizId = r.body.id;
    });

    it('students cannot broadcast (403)', async () => {
      const res = await request(app.getHttpServer())
        .post(`/api/quizzes/${bquizId}/broadcast-telegram`)
        .set('Authorization', `Bearer ${studentToken}`)
        .send({});
      expect(res.status).toBe(403);
    });

    it('endpoint requires auth', async () => {
      const res = await request(app.getHttpServer()).post(`/api/quizzes/${bquizId}/broadcast-telegram`).send({});
      expect(res.status).toBe(401);
    });
  });
});
